#!/usr/bin/env bash
set -euo pipefail

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║    🏭  WM-811K Wafer Defect Classification Pipeline           ║"
echo "║        ✅ Codespace is Ready!                                  ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Quick Start (2 commands):"
echo ""
echo "  Step 1: Download Dataset"
echo "  ────────────────────────"
echo "      bash scripts/download_dataset.sh"
echo ""
echo "  Step 2: Run Pipeline"
echo "  ────────────────────"
echo "      python run_all.py"
echo ""
echo "💡 The download script auto-detects your Kaggle credentials"
echo "   (supports both uploaded kaggle.json or KAGGLE_JSON secret)"
echo ""
